// Generate the blind drill workbook from the main book.
//
// The bug cases and design problems are practice items, not reading material,
// but in the book each one sits directly above its own answer. Reading them in
// order therefore teaches recognition ("yes, that is a leak") while the
// interview asks for recall ("what is wrong with this?"). This strips every
// answer and leaves only the prompt, so an attempt has to happen first.
//
//   node make-drills.mjs   ->  drills.tex
//
// Extraction relies on two structural facts, asserted below rather than
// assumed: a bug case runs from \bugcase to the end of its single ktbug block,
// and a design problem runs from \designq to its 需求澄清 subsection, which is
// where the model answer starts.
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

// Chapter numbers below are the numbers as printed in main.pdf, not the file
// names: preface is unnumbered, so ch00-overview prints as chapter 1 and every
// chapters/chNN file prints as NN+1. Pointing a reader at the wrong chapter is
// the one error that makes a workbook worse than no workbook.
const ROOT = dirname(fileURLToPath(import.meta.url));
const CH = join(ROOT, 'chapters');

const BUG_FILES = [
  ['ch04-review-concurrency.tex', '协程、Flow 与并发'],
  ['ch05-review-lifecycle.tex', '生命周期、泄漏与列表'],
  ['ch06-review-compose-idiom.tex', 'Compose 与 Kotlin 惯用性'],
];
const DESIGN_FILES = [
  ['ch08-design-core.tex', '核心设计题'],
  ['ch09-design-advanced.tex', '进阶设计题'],
];

const read = (f) => readFileSync(join(CH, f), 'utf8');

/** Everything from one \macro{ occurrence to the next, last one to end of file. */
function slices(src, macro) {
  const starts = [...src.matchAll(new RegExp(`\\\\${macro}\\{`, 'g'))].map((m) => m.index);
  return starts.map((s, i) => src.slice(s, i + 1 < starts.length ? starts[i + 1] : src.length));
}

/** The three braced arguments of \bugcase{n}{title}{category}. */
function head(block, macro) {
  const m = block.match(new RegExp(`^\\\\${macro}\\{([^}]*)\\}\\{([^}]*)\\}\\{([^}]*)\\}`));
  if (!m) throw new Error(`could not parse ${macro} header: ${block.slice(0, 80)}`);
  return { n: m[1], title: m[2], cat: m[3], rest: block.slice(m[0].length) };
}

const bugs = [];
for (const [file, part] of BUG_FILES) {
  for (const block of slices(read(file), 'bugcase')) {
    const { n, title, cat, rest } = head(block, 'bugcase');
    const end = rest.indexOf('\\end{ktbug}');
    if (end < 0) throw new Error(`bug case ${n} has no ktbug block`);
    bugs.push({ n, title, cat, part, body: rest.slice(0, end + '\\end{ktbug}'.length).trim() });
  }
}

const designs = [];
for (const [file, part] of DESIGN_FILES) {
  for (const block of slices(read(file), 'designq')) {
    const { n, title, cat, rest } = head(block, 'designq');
    // The model answer begins at 需求澄清; everything before it is the prompt.
    const cut = rest.search(/\\subsection\{[^}]*需求澄清/);
    if (cut < 0) throw new Error(`design problem ${n} has no 需求澄清 subsection`);
    designs.push({ n, title, cat, part, body: rest.slice(0, cut).trim() });
  }
}

// A silently short workbook would be worse than a failure: it would look
// complete while quietly dropping practice items.
if (bugs.length !== 17) throw new Error(`expected 17 bug cases, extracted ${bugs.length}`);
if (designs.length !== 9) throw new Error(`expected 9 design problems, extracted ${designs.length}`);

const strip = (s) => s.replace(/^%.*$/gm, '').replace(/\n{3,}/g, '\n\n').trim();

let part = '';
const bugSections = bugs.map((b) => {
  const head = b.part === part ? '' : `\n\\part{查错演练：${b.part}}\n`;
  part = b.part;
  return `${head}
\\bugcase{${b.n}}{${b.title}}{${b.cat}}

${strip(b.body)}

\\begin{drill}
写下你的评审。按优先级排序，每条给出：\\textbf{影响} / \\textbf{触发条件} / \\textbf{具体改法}。
写完再翻正式书第${b.n <= 6 ? '五' : b.n <= 12 ? '六' : '七'}章对答案。
\\end{drill}

\\vspace{2em}
`;
}).join('\n');

part = '';
const designSections = designs.map((d) => {
  const head = d.part === part ? '' : `\n\\part{设计演练：${d.part}}\n`;
  part = d.part;
  return `${head}
\\designq{${d.n}}{${d.title}}{${d.cat}}

${strip(d.body)}

\\begin{drill}
限时 10 分钟口述（建议录音）。先问澄清问题，再画模块图，最后讲存储、离线、失败与回滚。
写完再翻正式书第${d.n <= 4 ? '九' : '十'}章对答案。
\\end{drill}

\\vspace{2em}
`;
}).join('\n');

const out = `% Generated by make-drills.mjs -- do not edit by hand.
\\documentclass[11pt,a4paper,oneside]{book}
\\input{preamble}

\\newtcolorbox{drill}{
  enhanced, breakable, colback=white, colframe=abgray!60,
  boxrule=0.5pt, arc=2pt, left=8pt, right=8pt, top=6pt, bottom=6pt,
  borderline west={2.5pt}{0pt}{duogreen},
  fontupper=\\small
}

\\title{多邻国 Android 面试 · 遮蔽版习题册}
\\author{}
\\date{}

\\begin{document}

\\begin{titlepage}
\\centering
\\vspace*{5cm}
{\\Huge\\bfseries\\color{duogreen} 遮蔽版习题册\\par}
\\vspace{0.8cm}
{\\Large 多邻国 Android 面试 · 17 道查错 + 9 道设计\\par}
\\vspace{2cm}
\\begin{minipage}{0.75\\textwidth}
\\small
本册只有题面，没有答案。\\par\\vspace{0.6em}
查错题和设计题在正式书里与答案同页，顺着读会让人产生“我看得懂”的错觉——
但那是\\textbf{再认}，面试考的是\\textbf{回忆}。请先在这里写出你的评审，
再回正式书对答案；两者的差集就是你真正要补的东西。\\par\\vspace{0.6em}
建议：每题限时 8--10 分钟，出声说，或者写成英文 review comment。
\\end{minipage}
\\end{titlepage}

\\tableofcontents

\\chapter*{怎么用这本册子}
\\addcontentsline{toc}{chapter}{怎么用这本册子}

\\textbf{查错题（17 道）}：读代码，写出你会提的每一条意见。按优先级排序，
每条必须包含三样东西——\\textbf{影响}（用户会怎样）、\\textbf{触发条件}（什么情况下发生）、
\\textbf{具体改法}（一句话说清楚怎么改）。只写“这里有问题”不算数。

\\textbf{设计题（9 道）}：限时 10 分钟口述并录音。顺序是：澄清问题 $\\to$ 模块图 $\\to$
数据与存储 $\\to$ 离线与同步 $\\to$ 失败与回滚 $\\to$ 测试与灰度。

\\textbf{评分方式}：对完答案后，把你\\textbf{没想到}的每一条抄进一张错题表，
并标注它属于哪一类——是不认得这个 API，还是没有养成那个提问习惯。
第二类才是需要专门练的。

\\textbf{一点说明}：题面保留了正式书里的场景描述，个别题会顺带点出改动涉及的 API。
这不算剧透——你要写的是一份\\textbf{完整且排好序的评审}，不是猜一个关键词。
知道“这题和协程作用域有关”，离说清楚影响、触发条件和改法还差得远。

\\vspace{1em}
\\begin{keypoint}[一个自测门槛]
面试前，随机抽 5 道查错题，每道 8 分钟。如果平均能报出\\textbf{最高优先级的那一条}，
并且给得出具体改法，这一轮基本稳了。报不出来的题，回去看正式书对应章节的“根因分析”。
\\end{keypoint}

${bugSections}

${designSections}

\\end{document}
`;

writeFileSync(join(ROOT, 'drills.tex'), out);
console.log(`wrote drills.tex  (${bugs.length} bug cases, ${designs.length} design problems)`);
